EBookstore/Models/Bookstore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EBookstore.Models
{
    public class Bookstore
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Bookstore")]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Street { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        public List<Book> Books { get; set; }
    }
}

EBookstore/Controllers/BookstoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBookstore.Models;

namespace EBookstore.Controllers
{
    public class BookstoresController : Controller
    {
        private EBookstoreContext db = new EBookstoreContext();

        // GET: Bookstores
        public ActionResult Index()
        {
            return View(db.Bookstores.ToList());
        }

        // GET: Bookstores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookstore bookstore = db.Bookstores.Find(id);
            if (bookstore == null)
            {
                return HttpNotFound();
            }
            return View(bookstore);
        }

        // GET: Bookstores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bookstores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Street,City")] Bookstore bookstore)
        {
            if (ModelState.IsValid)
            {
                db.Bookstores.Add(bookstore);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bookstore);
        }

        // GET: Bookstores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookstore bookstore = db.Bookstores.Find(id);
            if (bookstore == null)
            {
                return HttpNotFound();
            }
            return View(bookstore);
        }

        // POST: Bookstores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Street,City")] Bookstore bookstore)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookstore).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookstore);
        }

        // GET: Bookstores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookstore bookstore = db.Bookstores.Find(id);
            if (bookstore == null)
            {
                return HttpNotFound();
            }
            return View(bookstore);
        }

        // POST: Bookstores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bookstore bookstore = db.Bookstores.Find(id);
            db.Bookstores.Remove(bookstore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBookstore/Views/Bookstores/Create.cshtml
@model EBookstore.Models.Bookstore

@{
    ViewBag.Title = "Create";
}
<div class="page-header">
    <h2>New bookstore</h2>
</div>

@using (Html.BeginForm("Create", "Bookstores", FormMethod.Post, new { id = "formCreate"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "name", placeholder = "Bookstore name" } })
                <div id="nameError" class="hidden">Naziv mora imati vise od 5 karaktera!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control", id = "street", placeholder = "Bookstore street" } })
                <div id="streetError" class="hidden">Naziv ulice mora imati vise od 5 karaktera!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", id = "city", placeholder = "Bookstore city" } })
                <div id="cityError" class="hidden">Naziv grada mora imati vise od 4 karaktera</div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="buttonPress" type="button" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/left-arrow.png"/></span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/BookstoreValidator.js"></script>
}

EBookstore/Views/Bookstores/Delete.cshtml
@model EBookstore.Models.Bookstore

@{
    ViewBag.Title = "Delete";
}
<div class="page-header">
    <h2>Delete</h2>
</div>
<h4>Are you sure you want to delete this?</h4>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index")">
                <span><img src="~/Filter icon/left-arrow.png"/></span>
            </a> |
            <input type="submit" value="Delete" class="btn btn-danger" /> 
        </div>
    }
</div>

EBookstore/Views/Bookstores/Details.cshtml
@model EBookstore.Models.Bookstore

@{
    ViewBag.Title = "Details";
}
<div class="page-header">
    <h2>Details</h2>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/left-arrow.png"/></span>
    </a> |
    <a href="@Url.Action("Edit", new { id = Model.Id})" class="btn btn-warning btn-sm">
        <span class="glyphicon glyphicon-pencil"></span>
    </a>
</p>

EBookstore/Views/Bookstores/Edit.cshtml
@model EBookstore.Models.Bookstore

@{
    ViewBag.Title = "Edit";
}
<div class="page-header">
    <h2>Edit</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/left-arrow.png"/></span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EBookstore/Views/Bookstores/Index.cshtml
@model IEnumerable<EBookstore.Models.Bookstore>

@{
    ViewBag.Title = "Index";
}
<div class="page-header">
    <h2>Bookstores</h2>
</div>
<p>
    <a href="@Url.Action("Create")">
        <span><img src="~/Filter icon/plus.png" /></span>    
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id = item.Id})" class="btn btn-warning btn-sm">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a href="@Url.Action("Details", new { id = item.Id})" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-info-sign"></span>
            </a>
            <a href="@Url.Action("Delete", new { id = item.Id})" class="btn btn-danger btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        </td>
    </tr>
}

</table>