EBookstore/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EBookstore.Models
{
    public enum Genre
    {
        Science,
        Horror,
        Comedy,
        Crime,
        History
    }
    public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Author { get; set; }
        [Display(Name = "Genre")]
        public Genre genre { get; set; }
        [Required]
        [Range(0, double.MaxValue)]
        [Display(Name = "RSD")]
        public double Price { get; set; }
        [Required]
        public DateTime Created { get; set; }
        [ForeignKey("Bookstore")]
        public int BookstoreId { get; set; }
        public Bookstore Bookstore { get; set; }
    }
}

EBookstore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBookstore.Models;
using EBookstore.Models.Filter;
using Microsoft.Ajax.Utilities;
using PagedList;

namespace EBookstore.Controllers
{
    public class BooksController : Controller
    {
        private EBookstoreContext db = new EBookstoreContext();

        public enum Sorting
        {
            Name,
            Author,
            Price,
            Date
        }

        private static Dictionary<string, Sorting> sortDic = new Dictionary<string, Sorting>()
        {
            {"Name", Sorting.Name },
            {"Author", Sorting.Author },
            {"Price", Sorting.Price },
            {"Date", Sorting.Date }
        };

        SelectList list = new SelectList(sortDic, "Key", "Key", "Name");

        private int pageSize = 5;

        // GET: Books
        public ActionResult Index(BookFilter filter, string sortType = "Name", int pageNum=1)
        {
            IEnumerable<Book> allBooks = db.Books.Include(b => b.Bookstore);

            Sorting sortBy = sortDic[sortType];

            switch (sortBy)
            {
                case Sorting.Name:
                    allBooks = allBooks.OrderBy(b => b.Name);
                    break;
                case Sorting.Author:
                    allBooks = allBooks.OrderBy(b => b.Author);
                    break;
                case Sorting.Price:
                    allBooks = allBooks.OrderBy(b => b.Price);
                    break;
                case Sorting.Date:
                    allBooks = allBooks.OrderBy(b => b.Created);
                    break;
            }

            if(sortType == "")
            {
                sortType = "Name";
            }
            if (!filter.Name.IsNullOrWhiteSpace())
            {
                allBooks = allBooks.Where(f => f.Name.Contains(filter.Name));
            }
            if (!filter.Author.IsNullOrWhiteSpace())
            {
                allBooks = allBooks.Where(f => f.Author.Contains(filter.Author));
            }
            if(filter.Price != 0.00)
            {
                allBooks = allBooks.Where(f => f.Price == filter.Price);
            }
            ViewBag.CurrentFilter = filter;
            ViewBag.CurrentSortType = sortType;
            ViewBag.Sorting = list;
            return View(allBooks.ToPagedList(pageNum, pageSize));

        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.BookstoreId = new SelectList(db.Bookstores, "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Author,genre,Price,Created,BookstoreId")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookstoreId = new SelectList(db.Bookstores, "Id", "Name", book.BookstoreId);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookstoreId = new SelectList(db.Bookstores, "Id", "Name", book.BookstoreId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Author,genre,Price,Created,BookstoreId")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookstoreId = new SelectList(db.Bookstores, "Id", "Name", book.BookstoreId);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBookstore/Views/Books/Create.cshtml
@model EBookstore.Models.Book

@{
    ViewBag.Title = "Create";
}
<div class="page-header">
    <h2>New book</h2>
</div>

@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { id = "formCreate" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id ="name", placeholder = "Book name" } })
                <div id="nameError" class="hidden">Morate uneti vise od 3 karaktera!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control", id ="author", placeholder = "Author name" } })
                <div id="authorError" class="hidden">Morate uneti vise od 5 karaktera!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.genre, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", id ="price", placeholder = "1299" } })
                <div id="priceError" class="hidden">Morate uneti cenu vecu od 200!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control", id ="date", placeholder = "MM/DD/YY" } })
                <div id="createdError" class="hidden">Nepostojeci datum!</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookstoreId, "Bookstore", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookstoreId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="submitButton" type="button" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/books.png" /></span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/BookValidator.js"></script>
}

EBookstore/Views/Books/Delete.cshtml
@model EBookstore.Models.Book

@{
    ViewBag.Title = "Delete";
}
<div class="page-header">
    <h2>Delete</h2>
</div>
<h4>Are you sure you want to delete this?</h4>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bookstore.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bookstore.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Books", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index")">
                <span><img src="~/Filter icon/left-arrow.png"/></span>
            </a> |
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            
        </div>
    }
</div>

EBookstore/Views/Books/Details.cshtml
@model EBookstore.Models.Book

@{
    ViewBag.Title = "Details";
}
<div class="page-header">
    <h2>Details</h2>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bookstore.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bookstore.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/left-arrow.png" /></span>
    </a>
    <a href="@Url.Action("Edit", new { id = Model.Id})" class="btn btn-warning btn-sm">
        <span class="glyphicon glyphicon-pencil"></span>
    </a>

</p>

EBookstore/Views/Books/Edit.cshtml
@model EBookstore.Models.Book

@{
    ViewBag.Title = "Edit";
}
<div class="page-header">
    <h2>Edit</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genre, "Genre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.genre, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookstoreId, "Bookstore", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookstoreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookstoreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")">
        <span><img src="~/Filter icon/left-arrow.png"/></span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EBookstore/Views/Books/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<EBookstore.Models.Book>

@{
                /**/

                ViewBag.Title = "Index";
}
<div class="page-header">
    <h2>Books</h2>
</div>

<p>
    <a href="@Url.Action("Create")">
        <span><img src="~/Filter icon/plus.png" /></span>
    </a>
</p>


<div>
    <div class="col-md-6">
        @using (Html.BeginForm("Index", "Books", FormMethod.Get))
        {
            @Html.DropDownList("sortType", ViewBag.Sorting as SelectList, new { @class = "form-control col-md-6" })
            <div>
                <input type="submit" value="Sort" class="btn btn-default btn-md" />
            </div>
        }
    </div>
</div>
<div class="col-md-12">
    <button class="btn btn-md btn-default" id="filter" type="button">
        <span class="glyphicon glyphicon-search"></span>
        Filter
    </button>
</div>


<div id="filterForm" class="hidden">
    <div class="col-lg-6">
        @using (Html.BeginForm("Index", "Books", FormMethod.Get))
        {
            @Html.Label("Name")
            @Html.TextBox("Name", null, new { @class = "form-control" })
            @Html.Label("Author")
            @Html.TextBox("Author", null, new { @class = "form-control" })
            @Html.Label("Price")
            @Html.TextBox("Price", null, new { @class = "form-control" })
            <br />
            <input type="submit" value="Filter" class="btn btn-success" />
        }
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Bookstore.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Created)
            </th>
            <th></th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Bookstore.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id = item.Id})" class="btn btn-warning btn-sm">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a href="@Url.Action("Details", new { id = item.Id})" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-info-sign"></span>
                </a>
                <a href="@Url.Action("Delete", new { id = item.Id})" class="btn btn-danger btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>

            </td>
        </tr>

    }

</table>

<center>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, pageNum => Url.Action("Index", new {
    Name = ViewBag.CurrentFilter.Name,
    Author = ViewBag.CurrentFilter.Author,
    Price = ViewBag.CurrentFilter.Price,
    pageNum, sortType =  ViewBag.CurrentSortType
}))
</center>

    @section Scripts{
        <script src="~/Scripts/MyFilter.js"></script>
    }
 